### ISSUE TITLE
List of objects does not serialize properly after flask upgrade from 1.0.3 to 1.1

### ISSUE THREAD

**Issue by PMLP-novo** [jmcarp/flask-apispec#160]
After changing to from version 1.0.3 to 1.1 my marshall with many code breaks. @ThiefMaster from the flask development team surgested transfering the issue to you. See https://github.com/pallets/flask/issues/3348 

```python
from marshmallow import fields
from flask import Blueprint
from flask_apispec import marshal_with, doc
from database import Team
from marshmallow import Schema


bp = Blueprint("team", __name__, url_prefix="/teams")


class TeamSchema(Schema):
    id = fields.Str(required=True, dump_only=True, example="1")
    name = fields.Str(required=True, example="123 Abc")


@bp.route("")
@marshal_with(TeamSchema(many=True), description="A list of teams.")
@doc(tags=["Team"])
def search():
    """Fetch the list of teams, ordered by name."""
    return Team.query.order_by("name")
```
 And gives the following error when invoked either by localhost/teams
`TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.`

When running when changing to flask 1.0.3 it works. Without an error

### Environment

* Python version: 3.6.8
* Flask version: 1.1
* Werkzeug version: 0.15.5
* marshmallow:  2.20.2
* flask-apispec: 2.0.2

**Comment by amickael** [comment]
Any update on this? I'm having the same issue.

**Comment by stufisher** [comment]
This does look to be related to flask-apispec. I iterated over the relevant conda packages with flask, flask-restful, marshmallow:
```
marshmallow               3.2.2 
flask                     1.1.1
flask-apispec             0.8.5
flask-restful             0.3.7
apispec                   3.1.0
```
updating to the latest marshmallow does not break this


This works with flask 1.1.1 and flask-apispec 0.8.6, however in  0.8.7 the error is:
```
Traceback (most recent call last):
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_apispec/annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 39, in __call__
    return self.marshal_result(unpacked, status_code)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 72, in marshal_result
    response_object.status_code = unpacked[1] or 200
AttributeError: 'dict' object has no attribute 'status_code'
```

and in >= 0.8.8:
```
Traceback (most recent call last):
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_apispec/annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask_apispec/wrapper.py", line 39, in __call__
    return flask.current_app.make_response(response)
  File "/opt/conda/envs/daiquiri/lib/python3.7/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
```
