### ISSUE TITLE
apispec==1.0.0 (that matches apispec>=0.39.0) incompatible

### ISSUE THREAD

**Issue by tiangolo** [jmcarp/flask-apispec#130]
Installing `flask-apispec` installs the latest version of `apispec` (`1.0.0`).

But in `1.0.0` the `APISpec` class seems to no longer have the method `add_path` that `flask-apispec` tries to use.

I guess the simplest (quickest) fix is to pin the range of `apispec` compatible versions in `setup.py`.

I guess the long-term fix would be more cumbersome.

Pinning `apispec` to `apispec==0.39.0` in the project solves it, as a workaround.

I'm using it in these project generators based on this:

https://github.com/tiangolo/full-stack-flask-couchbase
https://github.com/tiangolo/full-stack
https://github.com/tiangolo/full-stack-flask-couchdb

Here are the logs I'm getting while debugging it:

```
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/app/app/main.py", line 8, in <module>
from .core import app_setup  # noqa
File "/app/app/core/app_setup.py", line 8, in <module>
from ..api.api_v1 import api as api_v1  # noqa
File "/app/app/api/api_v1/api.py", line 1, in <module>
from .endpoints import role, token, user, utils  # noqa
File "/app/app/api/api_v1/endpoints/role.py", line 18, in <module>
@jwt_required
File "/usr/local/lib/python3.6/site-packages/flask_apispec/extension.py", line 119, in register
resource_class_args, resource_class_kwargs)
File "/usr/local/lib/python3.6/site-packages/flask_apispec/extension.py", line 66, in _defer
bound()
File "/usr/local/lib/python3.6/site-packages/flask_apispec/extension.py", line 146, in _register
self.spec.add_path(**path)
AttributeError: 'APISpec' object has no attribute 'add_path'
```

**Comment by DStape** [comment]
Hi @tiangolo,

I've just opened #131 that gets flask-apispec working with apispec 1.0, if you have the time would you mind giving it a try and seeing if it works for your usage/use-case? Thanks, David.

**Comment by sloria** [comment]
0.8.0 now supports apispec>=1.0.0

**Comment by tiangolo** [comment]
Sorry guys I couldn't check it. Thanks for fixing it!
